#pragma once

#include <tracktion_engine/tracktion_engine.h>

#include <atomic>
#include <vector>

namespace magda::daw::audio {

namespace te = tracktion::engine;

/**
 * StrudelPlugin — "Tidal" live-coding synth.
 *
 * Hosts the REAL Strudel engine (full @strudel package set + superdough) inside a
 * juce::WebBrowserComponent (WebView2). The editor IS the Strudel REPL UI. Audio is
 * generated by the WebView's Web Audio graph; a capture AudioWorklet taps the master
 * output and pushes Float32 PCM back to this plugin through a native function. That
 * PCM is drained on the audio thread in applyToBuffer() and mixed into the track, so
 * Strudel output can be monitored, mixed and recorded like any other instrument.
 *
 * Design notes:
 *  - Opening the editor is SILENT; sound only starts when the user presses Play
 *    (Ctrl+Enter) in the REPL. (Fixes the "sound on editor open" bug.)
 *  - The WebView lives in the editor; the lock-free PCM ring buffer lives here so the
 *    audio thread reads it independently of the message thread that fills it.
 *  - Incoming PCM is resampled from the WebAudio context rate to the track rate.
 */
class StrudelPlugin : public te::Plugin {
  public:
    explicit StrudelPlugin(const te::PluginCreationInfo&);
    ~StrudelPlugin() override;

    static const char* getPluginName() { return "Tidal"; }
    static const char* xmlTypeName;

    juce::String getName() const override { return getPluginName(); }
    juce::String getPluginType() override { return xmlTypeName; }
    juce::String getShortName(int) override { return "TIDAL"; }
    juce::String getSelectableDescription() override { return getName(); }

    void initialise(const te::PluginInitialisationInfo&) override;
    void deinitialise() override;
    void reset() override;
    void applyToBuffer(const te::PluginRenderContext&) override;

    std::unique_ptr<EditorComponent> createEditor() override;

    bool takesMidiInput() override { return false; }
    bool takesAudioInput() override { return false; }
    bool isSynth() override { return true; }
    bool producesAudioWhenNoAudioInput() override { return true; }
    double getTailLength() const override { return 0.0; }

    void restorePluginStateFromValueTree(const juce::ValueTree&) override;

    // Persisted REPL code (so the pattern text survives save / reload).
    juce::String getCode() const { return codeValue.get(); }
    void setCode(const juce::String& code) { codeValue = code; }
    juce::CachedValue<juce::String> codeValue;

    // Called on the message thread by the editor's WebView native-function bridge with
    // one stereo PCM chunk captured from Strudel's master output. Resamples to the
    // track rate and pushes into the lock-free ring buffer.
    void pushCapturedAudio(const float* left, const float* right, int numFrames,
                           double srcSampleRate);

  private:
    double sampleRate_ = 44100.0;

    // Lock-free stereo ring buffer (message thread writes, audio thread reads).
    static constexpr int kFifoCapacity = 1 << 16;  // 65536 frames (~1.4 s @ 44.1k)
    std::vector<float> fifoL_;
    std::vector<float> fifoR_;
    std::atomic<int> writePos_{0};
    std::atomic<int> readPos_{0};

    // Linear-resampler carry state (message thread only).
    double resamplePhase_ = 0.0;
    float prevL_ = 0.0f, prevR_ = 0.0f;
    bool havePrev_ = false;

    void clearFifo();

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(StrudelPlugin)
};

}  // namespace magda::daw::audio
