#include "SamplerFactoryPresets.hpp"

namespace magda::daw::audio {

const std::vector<SamplerPreset>& getSamplerFactoryPresets() {
    static const std::vector<SamplerPreset> presets = {
        // ====================================================================
        // DRUMS
        // ====================================================================
        {
            "Tight Kick",
            "Drums",
            "Punchy kick drum with fast attack and short decay",
            {
                {"attack", 0.001f},
                {"decay", 0.12f},
                {"sustain", 0.0f},
                {"release", 0.05f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 1.0f},
                {"loop_enabled", 0.0f},
                {"loop_start", 0.0f},
                {"loop_end", 1.0f},
                {"velocity_amount", 0.8f},
                {"volume", 0.85f},
            },
        },
        {
            "Snappy Snare",
            "Drums",
            "Crisp snare with sharp transient and short body",
            {
                {"attack", 0.0f},
                {"decay", 0.18f},
                {"sustain", 0.0f},
                {"release", 0.08f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 1.0f},
                {"loop_enabled", 0.0f},
                {"loop_start", 0.0f},
                {"loop_end", 1.0f},
                {"velocity_amount", 0.9f},
                {"volume", 0.8f},
            },
        },
        {
            "Crisp HiHat",
            "Drums",
            "Tight hi-hat with very short decay and high pitch offset",
            {
                {"attack", 0.0f},
                {"decay", 0.06f},
                {"sustain", 0.0f},
                {"release", 0.03f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 0.5f},
                {"loop_enabled", 0.0f},
                {"loop_start", 0.0f},
                {"loop_end", 1.0f},
                {"velocity_amount", 0.7f},
                {"volume", 0.7f},
            },
        },
        {
            "One Shot",
            "Drums",
            "Full velocity one-shot trigger with no loop or sustain",
            {
                {"attack", 0.0f},
                {"decay", 0.5f},
                {"sustain", 0.0f},
                {"release", 0.02f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 1.0f},
                {"loop_enabled", 0.0f},
                {"loop_start", 0.0f},
                {"loop_end", 1.0f},
                {"velocity_amount", 1.0f},
                {"volume", 0.9f},
            },
        },
        // ====================================================================
        // KEYS
        // ====================================================================
        {
            "Piano Sustain",
            "Keys",
            "Natural piano envelope with medium attack and long release",
            {
                {"attack", 0.008f},
                {"decay", 0.6f},
                {"sustain", 0.3f},
                {"release", 0.8f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 1.0f},
                {"loop_enabled", 0.0f},
                {"loop_start", 0.0f},
                {"loop_end", 1.0f},
                {"velocity_amount", 0.85f},
                {"volume", 0.75f},
            },
        },
        {
            "Organ Hold",
            "Keys",
            "Instant attack with full sustain for organ-style playback",
            {
                {"attack", 0.001f},
                {"decay", 0.05f},
                {"sustain", 1.0f},
                {"release", 0.06f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 1.0f},
                {"loop_enabled", 1.0f},
                {"loop_start", 0.1f},
                {"loop_end", 0.9f},
                {"velocity_amount", 0.3f},
                {"volume", 0.7f},
            },
        },
        // ====================================================================
        // STRINGS
        // ====================================================================
        {
            "Bowed String",
            "Strings",
            "Slow bowing attack with full sustain and looped playback",
            {
                {"attack", 0.35f},
                {"decay", 0.2f},
                {"sustain", 0.85f},
                {"release", 0.4f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 1.0f},
                {"loop_enabled", 1.0f},
                {"loop_start", 0.15f},
                {"loop_end", 0.85f},
                {"velocity_amount", 0.6f},
                {"volume", 0.7f},
            },
        },
        {
            "Pizzicato",
            "Strings",
            "Quick plucked string with fast attack and short decay",
            {
                {"attack", 0.0f},
                {"decay", 0.22f},
                {"sustain", 0.0f},
                {"release", 0.15f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 1.0f},
                {"loop_enabled", 0.0f},
                {"loop_start", 0.0f},
                {"loop_end", 1.0f},
                {"velocity_amount", 0.75f},
                {"volume", 0.75f},
            },
        },
        // ====================================================================
        // PADS
        // ====================================================================
        {
            "Ambient Pad",
            "Pads",
            "Very slow attack with long release and looped sustain",
            {
                {"attack", 0.8f},
                {"decay", 0.4f},
                {"sustain", 0.7f},
                {"release", 1.2f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 1.0f},
                {"loop_enabled", 1.0f},
                {"loop_start", 0.2f},
                {"loop_end", 0.8f},
                {"velocity_amount", 0.4f},
                {"volume", 0.65f},
            },
        },
        {
            "Evolving Texture",
            "Pads",
            "Slow attack with looped region for evolving timbral movement",
            {
                {"attack", 0.6f},
                {"decay", 0.5f},
                {"sustain", 0.6f},
                {"release", 1.0f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 1.0f},
                {"loop_enabled", 1.0f},
                {"loop_start", 0.1f},
                {"loop_end", 0.95f},
                {"velocity_amount", 0.35f},
                {"volume", 0.6f},
            },
        },
        // ====================================================================
        // BASS
        // ====================================================================
        {
            "Plucked Bass",
            "Bass",
            "Fast attack with medium decay for plucked bass sounds",
            {
                {"attack", 0.002f},
                {"decay", 0.35f},
                {"sustain", 0.15f},
                {"release", 0.12f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 1.0f},
                {"loop_enabled", 0.0f},
                {"loop_start", 0.0f},
                {"loop_end", 1.0f},
                {"velocity_amount", 0.8f},
                {"volume", 0.8f},
            },
        },
        {
            "Sustained Bass",
            "Bass",
            "Fast attack with full sustain and loop for held bass notes",
            {
                {"attack", 0.005f},
                {"decay", 0.1f},
                {"sustain", 0.9f},
                {"release", 0.1f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 1.0f},
                {"loop_enabled", 1.0f},
                {"loop_start", 0.1f},
                {"loop_end", 0.9f},
                {"velocity_amount", 0.7f},
                {"volume", 0.8f},
            },
        },
        // ====================================================================
        // VOCAL
        // ====================================================================
        {
            "Vocal Chop",
            "Vocal",
            "Instant attack with short decay for rhythmic vocal slicing",
            {
                {"attack", 0.0f},
                {"decay", 0.2f},
                {"sustain", 0.0f},
                {"release", 0.05f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 0.6f},
                {"loop_enabled", 0.0f},
                {"loop_start", 0.0f},
                {"loop_end", 1.0f},
                {"velocity_amount", 0.9f},
                {"volume", 0.8f},
            },
        },
        {
            "Choir Sustain",
            "Vocal",
            "Medium attack with looped sustain for choir-style pads",
            {
                {"attack", 0.25f},
                {"decay", 0.3f},
                {"sustain", 0.75f},
                {"release", 0.5f},
                {"pitch", 0.0f},
                {"fine_tune", 0.0f},
                {"sample_start", 0.0f},
                {"sample_end", 1.0f},
                {"loop_enabled", 1.0f},
                {"loop_start", 0.15f},
                {"loop_end", 0.85f},
                {"velocity_amount", 0.5f},
                {"volume", 0.7f},
            },
        },
    };
    return presets;
}

}  // namespace magda::daw::audio