#include "four_osc_factory_presets.hpp"

namespace magda {

const std::vector<FourOscAgent::Preset>& getFactoryFourOscPresets() {
    static const std::vector<FourOscAgent::Preset> presets = {
        // ====================================================================
        // KEYS
        // ====================================================================
        {
            "Electric Piano",
            "Keys",
            "Warm Rhodes-style electric piano with gentle attack and soft release",
            {
                {"amp_attack", 0.01f},
                {"amp_decay", 0.35f},
                {"amp_sustain", 45.0f},
                {"amp_release", 0.25f},
                {"level_1", -4.6f},
                {"level_2", -6.0f},
                {"level_3", -14.0f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"tune_2", 0.0f},
                {"tune_3", 0.0f},
                {"detune_1", 0.000f},
                {"detune_2", 0.040f},
                {"detune_3", 0.040f},
                {"filter_freq", 113.3f},
                {"filter_resonance", 15.0f},
                {"filter_env_amount", 30.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.3f},
                {"filter_sustain", 20.0f},
                {"filter_release", 0.2f},
                {"master_level", -8.2f},
            },
            {{1, "sine"}, {2, "sine"}, {3, "triangle"}, {4, "none"}},
            "lp",
            "poly",
            {{"reverb", true}, {"chorus", true}},
        },
        {
            "Acoustic Piano",
            "Keys",
            "Bright acoustic piano simulation with hammer-like attack",
            {
                {"amp_attack", 0.005f},
                {"amp_decay", 0.55f},
                {"amp_sustain", 25.0f},
                {"amp_release", 0.35f},
                {"level_1", -4.0f},
                {"level_2", -5.2f},
                {"level_3", -10.5f},
                {"level_4", -18.4f},
                {"tune_1", 0.0f},
                {"tune_2", 12.0f},
                {"tune_3", 6.0f},
                {"tune_4", 3.0f},
                {"detune_1", 0.000f},
                {"detune_2", 0.002f},
                {"detune_3", 0.002f},
                {"detune_4", 0.004f},
                {"filter_freq", 120.3f},
                {"filter_resonance", 8.0f},
                {"filter_env_amount", 25.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.4f},
                {"filter_sustain", 15.0f},
                {"filter_release", 0.3f},
                {"master_level", -7.7f},
            },
            {{1, "sine"}, {2, "sine"}, {3, "sine"}, {4, "triangle"}},
            "lp",
            "poly",
            {{"reverb", true}},
        },
        {
            "Organ",
            "Keys",
            "Classic drawbar organ with warm harmonics",
            {
                {"amp_attack", 0.01f},
                {"amp_decay", 0.1f},
                {"amp_sustain", 90.0f},
                {"amp_release", 0.08f},
                {"level_1", -5.0f},
                {"level_2", -4.4f},
                {"level_3", -8.0f},
                {"level_4", -10.5f},
                {"tune_1", 0.0f},
                {"tune_2", 12.0f},
                {"tune_3", 6.0f},
                {"tune_4", 3.0f},
                {"detune_1", 0.000f},
                {"detune_2", 0.000f},
                {"detune_3", 0.000f},
                {"detune_4", 0.000f},
                {"filter_freq", 125.0f},
                {"filter_resonance", 5.0f},
                {"filter_env_amount", 0.0f},
                {"master_level", -8.2f},
            },
            {{1, "sine"}, {2, "sine"}, {3, "sine"}, {4, "sine"}},
            "off",
            "poly",
            {{"chorus", true}, {"reverb", true}},
        },
        {
            "Clavinet",
            "Keys",
            "Funky clavinet with sharp attack and bright tone",
            {
                {"amp_attack", 0.0f},
                {"amp_decay", 0.3f},
                {"amp_sustain", 30.0f},
                {"amp_release", 0.1f},
                {"level_1", -4.0f},
                {"level_2", -4.4f},
                {"level_3", -10.5f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"tune_2", 12.0f},
                {"tune_3", 0.0f},
                {"detune_1", 0.000f},
                {"detune_2", 0.004f},
                {"filter_freq", 121.5f},
                {"filter_resonance", 20.0f},
                {"filter_env_amount", 40.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.2f},
                {"filter_sustain", 10.0f},
                {"filter_release", 0.1f},
                {"master_level", -8.2f},
            },
            {{1, "square"}, {2, "square"}, {3, "saw_up"}, {4, "none"}},
            "lp",
            "poly",
            {},
        },
        // ====================================================================
        // BASS
        // ====================================================================
        {
            "Sub Bass",
            "Bass",
            "Deep sub bass with tight envelope for electronic music",
            {
                {"amp_attack", 0.005f},
                {"amp_decay", 0.2f},
                {"amp_sustain", 90.0f},
                {"amp_release", 0.1f},
                {"level_1", -3.1f},
                {"level_2", -8.0f},
                {"level_3", -100.0f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"tune_2", 0.0f},
                {"detune_1", 0.000f},
                {"detune_2", 0.000f},
                {"filter_freq", 95.8f},
                {"filter_resonance", 10.0f},
                {"filter_env_amount", 10.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.15f},
                {"filter_sustain", 80.0f},
                {"filter_release", 0.1f},
                {"master_level", -7.1f},
            },
            {{1, "sine"}, {2, "square"}, {3, "none"}, {4, "none"}},
            "lp",
            "mono",
            {},
        },
        {
            "Reese Bass",
            "Bass",
            "Detuned saw bass with movement for DnB and dubstep",
            {
                {"amp_attack", 0.01f},
                {"amp_decay", 0.15f},
                {"amp_sustain", 85.0f},
                {"amp_release", 0.12f},
                {"level_1", -4.0f},
                {"level_2", -0.9f},
                {"level_3", -6.0f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"tune_2", 0.0f},
                {"tune_3", 0.0f},
                {"detune_1", 0.060f},
                {"detune_2", 0.060f},
                {"detune_3", 0.000f},
                {"filter_freq", 98.2f},
                {"filter_resonance", 20.0f},
                {"filter_env_amount", 15.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.3f},
                {"filter_sustain", 60.0f},
                {"filter_release", 0.15f},
                {"master_level", -7.7f},
            },
            {{1, "saw_up"}, {2, "saw_up"}, {3, "square"}, {4, "none"}},
            "lp",
            "mono",
            {{"distortion", true}},
        },
        {
            "Acid Bass",
            "Bass",
            "Classic 303-style acid bass with resonant filter sweep",
            {
                {"amp_attack", 0.0f},
                {"amp_decay", 0.15f},
                {"amp_sustain", 70.0f},
                {"amp_release", 0.05f},
                {"level_1", -3.1f},
                {"level_2", -100.0f},
                {"level_3", -100.0f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"filter_freq", 93.5f},
                {"filter_resonance", 70.0f},
                {"filter_env_amount", 60.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.2f},
                {"filter_sustain", 10.0f},
                {"filter_release", 0.05f},
                {"master_level", -7.7f},
            },
            {{1, "saw_up"}, {2, "none"}, {3, "none"}, {4, "none"}},
            "lp",
            "mono",
            {{"distortion", true}},
        },
        {
            "Finger Bass",
            "Bass",
            "Warm fingered bass guitar emulation",
            {
                {"amp_attack", 0.005f},
                {"amp_decay", 0.4f},
                {"amp_sustain", 30.0f},
                {"amp_release", 0.2f},
                {"level_1", -4.0f},
                {"level_2", -8.0f},
                {"level_3", -16.5f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"tune_2", 0.0f},
                {"tune_3", 6.0f},
                {"detune_1", 0.000f},
                {"detune_2", 0.002f},
                {"filter_freq", 101.7f},
                {"filter_resonance", 12.0f},
                {"filter_env_amount", 35.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.25f},
                {"filter_sustain", 15.0f},
                {"filter_release", 0.15f},
                {"master_level", -7.7f},
            },
            {{1, "sine"}, {2, "triangle"}, {3, "sine"}, {4, "none"}},
            "lp",
            "mono",
            {},
        },
        // ====================================================================
        // LEAD
        // ====================================================================
        {
            "Supersaw Lead",
            "Lead",
            "Bright detuned supersaw for EDM leads and hooks",
            {
                {"amp_attack", 0.02f},
                {"amp_decay", 0.2f},
                {"amp_sustain", 75.0f},
                {"amp_release", 0.15f},
                {"level_1", -5.0f},
                {"level_2", -1.9f},
                {"level_3", -4.4f},
                {"level_4", -6.0f},
                {"tune_1", 0.0f},
                {"tune_2", 0.0f},
                {"tune_3", 0.0f},
                {"tune_4", 0.0f},
                {"detune_1", 0.100f},
                {"detune_2", 0.100f},
                {"detune_3", 0.160f},
                {"detune_4", 0.160f},
                {"filter_freq", 116.8f},
                {"filter_resonance", 25.0f},
                {"filter_env_amount", 20.0f},
                {"filter_attack", 0.01f},
                {"filter_decay", 0.25f},
                {"filter_sustain", 50.0f},
                {"filter_release", 0.15f},
                {"master_level", -8.2f},
            },
            {{1, "saw_up"}, {2, "saw_up"}, {3, "saw_up"}, {4, "saw_up"}},
            "lp",
            "poly",
            {{"reverb", true}, {"delay", true}},
        },
        {
            "Square Lead",
            "Lead",
            "Retro square wave lead with slight portamento feel",
            {
                {"amp_attack", 0.01f},
                {"amp_decay", 0.1f},
                {"amp_sustain", 80.0f},
                {"amp_release", 0.1f},
                {"level_1", -4.0f},
                {"level_2", -8.0f},
                {"level_3", -100.0f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"tune_2", 12.0f},
                {"detune_1", 0.000f},
                {"detune_2", 0.020f},
                {"filter_freq", 109.8f},
                {"filter_resonance", 15.0f},
                {"filter_env_amount", 20.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.2f},
                {"filter_sustain", 40.0f},
                {"filter_release", 0.1f},
                {"master_level", -8.2f},
            },
            {{1, "square"}, {2, "square"}, {3, "none"}, {4, "none"}},
            "lp",
            "mono",
            {{"delay", true}},
        },
        {
            "Screaming Lead",
            "Lead",
            "Aggressive high-resonance lead for solos",
            {
                {"amp_attack", 0.0f},
                {"amp_decay", 0.1f},
                {"amp_sustain", 90.0f},
                {"amp_release", 0.08f},
                {"level_1", -3.1f},
                {"level_2", -3.1f},
                {"level_3", -100.0f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"tune_2", 0.0f},
                {"detune_1", 0.040f},
                {"detune_2", 0.040f},
                {"filter_freq", 107.5f},
                {"filter_resonance", 60.0f},
                {"filter_env_amount", 30.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.15f},
                {"filter_sustain", 60.0f},
                {"filter_release", 0.1f},
                {"master_level", -8.9f},
            },
            {{1, "saw_up"}, {2, "saw_up"}, {3, "none"}, {4, "none"}},
            "lp",
            "mono",
            {{"distortion", true}, {"delay", true}},
        },
        // ====================================================================
        // PAD
        // ====================================================================
        {
            "Warm Pad",
            "Pad",
            "Lush evolving pad with slow attack and rich harmonics",
            {
                {"amp_attack", 0.4f},
                {"amp_decay", 0.3f},
                {"amp_sustain", 70.0f},
                {"amp_release", 0.5f},
                {"level_1", -6.2f},
                {"level_2", -3.1f},
                {"level_3", -6.0f},
                {"level_4", -10.5f},
                {"tune_1", 0.0f},
                {"tune_2", 0.0f},
                {"tune_3", 0.0f},
                {"tune_4", 0.0f},
                {"detune_1", 0.040f},
                {"detune_2", 0.040f},
                {"detune_3", 0.060f},
                {"detune_4", 0.060f},
                {"filter_freq", 107.5f},
                {"filter_resonance", 20.0f},
                {"filter_env_amount", 15.0f},
                {"filter_attack", 0.5f},
                {"filter_decay", 0.3f},
                {"filter_sustain", 60.0f},
                {"filter_release", 0.5f},
                {"master_level", -8.9f},
            },
            {{1, "saw_up"}, {2, "saw_up"}, {3, "square"}, {4, "triangle"}},
            "lp",
            "poly",
            {{"reverb", true}, {"chorus", true}},
        },
        {
            "Glass Pad",
            "Pad",
            "Ethereal shimmering pad with high harmonics",
            {
                {"amp_attack", 0.6f},
                {"amp_decay", 0.4f},
                {"amp_sustain", 60.0f},
                {"amp_release", 0.8f},
                {"level_1", -9.1f},
                {"level_2", -3.1f},
                {"level_3", -4.4f},
                {"level_4", -8.0f},
                {"tune_1", 0.0f},
                {"tune_2", 12.0f},
                {"tune_3", 6.0f},
                {"tune_4", 3.0f},
                {"detune_1", 0.020f},
                {"detune_2", 0.020f},
                {"detune_3", 0.040f},
                {"detune_4", 0.040f},
                {"filter_freq", 119.2f},
                {"filter_resonance", 10.0f},
                {"filter_env_amount", 10.0f},
                {"filter_attack", 0.8f},
                {"filter_decay", 0.5f},
                {"filter_sustain", 70.0f},
                {"filter_release", 0.8f},
                {"master_level", -9.6f},
            },
            {{1, "triangle"}, {2, "sine"}, {3, "sine"}, {4, "triangle"}},
            "lp",
            "poly",
            {{"reverb", true}, {"chorus", true}, {"delay", true}},
        },
        {
            "Dark Ambient",
            "Pad",
            "Deep dark ambient texture with slow movement",
            {
                {"amp_attack", 0.8f},
                {"amp_decay", 0.5f},
                {"amp_sustain", 50.0f},
                {"amp_release", 1.0f},
                {"level_1", -7.5f},
                {"level_2", -4.4f},
                {"level_3", -8.0f},
                {"level_4", -10.5f},
                {"tune_1", 0.0f},
                {"tune_2", 0.0f},
                {"tune_3", -6.0f},
                {"tune_4", 0.0f},
                {"detune_1", 0.060f},
                {"detune_2", 0.060f},
                {"detune_3", 0.080f},
                {"detune_4", 0.080f},
                {"filter_freq", 95.8f},
                {"filter_resonance", 15.0f},
                {"filter_env_amount", 10.0f},
                {"filter_attack", 1.0f},
                {"filter_decay", 0.5f},
                {"filter_sustain", 40.0f},
                {"filter_release", 0.8f},
                {"master_level", -9.6f},
            },
            {{1, "saw_up"}, {2, "saw_down"}, {3, "triangle"}, {4, "noise"}},
            "lp",
            "poly",
            {{"reverb", true}, {"delay", true}},
        },
        {
            "Strings Ensemble",
            "Pad",
            "Lush string section with natural bow attack",
            {
                {"amp_attack", 0.25f},
                {"amp_decay", 0.2f},
                {"amp_sustain", 80.0f},
                {"amp_release", 0.3f},
                {"level_1", -6.2f},
                {"level_2", -3.1f},
                {"level_3", -6.0f},
                {"level_4", -10.5f},
                {"tune_1", 0.0f},
                {"tune_2", 0.0f},
                {"tune_3", 0.0f},
                {"tune_4", 0.0f},
                {"detune_1", 0.020f},
                {"detune_2", 0.020f},
                {"detune_3", 0.040f},
                {"detune_4", 0.040f},
                {"filter_freq", 109.8f},
                {"filter_resonance", 8.0f},
                {"filter_env_amount", 15.0f},
                {"filter_attack", 0.2f},
                {"filter_decay", 0.3f},
                {"filter_sustain", 50.0f},
                {"filter_release", 0.3f},
                {"master_level", -8.9f},
            },
            {{1, "saw_up"}, {2, "saw_up"}, {3, "saw_up"}, {4, "saw_up"}},
            "lp",
            "poly",
            {{"reverb", true}, {"chorus", true}},
        },
        // ====================================================================
        // PLUCK
        // ====================================================================
        {
            "Pluck",
            "Pluck",
            "Short percussive pluck for arpeggios and melodic sequences",
            {
                {"amp_attack", 0.0f},
                {"amp_decay", 0.2f},
                {"amp_sustain", 0.0f},
                {"amp_release", 0.15f},
                {"level_1", -4.0f},
                {"level_2", -6.0f},
                {"level_3", -12.0f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"tune_2", 0.0f},
                {"tune_3", 6.0f},
                {"detune_1", 0.000f},
                {"detune_2", 0.020f},
                {"detune_3", 0.000f},
                {"filter_freq", 119.2f},
                {"filter_resonance", 30.0f},
                {"filter_env_amount", 50.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.18f},
                {"filter_sustain", 0.0f},
                {"filter_release", 0.12f},
                {"master_level", -8.2f},
            },
            {{1, "saw_up"}, {2, "triangle"}, {3, "square"}, {4, "none"}},
            "lp",
            "poly",
            {{"delay", true}},
        },
        {
            "Harp Pluck",
            "Pluck",
            "Gentle harp-like pluck with long tail",
            {
                {"amp_attack", 0.0f},
                {"amp_decay", 0.5f},
                {"amp_sustain", 0.0f},
                {"amp_release", 0.4f},
                {"level_1", -5.0f},
                {"level_2", -8.0f},
                {"level_3", -14.0f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"tune_2", 12.0f},
                {"tune_3", 6.0f},
                {"detune_1", 0.000f},
                {"detune_2", 0.002f},
                {"filter_freq", 116.8f},
                {"filter_resonance", 10.0f},
                {"filter_env_amount", 40.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.4f},
                {"filter_sustain", 0.0f},
                {"filter_release", 0.3f},
                {"master_level", -8.2f},
            },
            {{1, "triangle"}, {2, "sine"}, {3, "sine"}, {4, "none"}},
            "lp",
            "poly",
            {{"reverb", true}},
        },
        {
            "Marimba",
            "Pluck",
            "Wooden marimba-like tone with quick decay",
            {
                {"amp_attack", 0.0f},
                {"amp_decay", 0.3f},
                {"amp_sustain", 0.0f},
                {"amp_release", 0.2f},
                {"level_1", -4.0f},
                {"level_2", -10.5f},
                {"level_3", -16.5f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"tune_2", 24.0f},
                {"tune_3", 6.0f},
                {"detune_1", 0.000f},
                {"detune_2", 0.000f},
                {"filter_freq", 107.5f},
                {"filter_resonance", 5.0f},
                {"filter_env_amount", 30.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.15f},
                {"filter_sustain", 0.0f},
                {"filter_release", 0.1f},
                {"master_level", -8.2f},
            },
            {{1, "sine"}, {2, "sine"}, {3, "triangle"}, {4, "none"}},
            "lp",
            "poly",
            {},
        },
        // ====================================================================
        // FX / TEXTURES
        // ====================================================================
        {
            "Noise Sweep",
            "FX",
            "White noise with filter sweep for risers and transitions",
            {
                {"amp_attack", 0.5f},
                {"amp_decay", 0.3f},
                {"amp_sustain", 60.0f},
                {"amp_release", 0.5f},
                {"level_1", -100.0f},
                {"level_2", -100.0f},
                {"level_3", -100.0f},
                {"level_4", -0.9f},
                {"filter_freq", 90.0f},
                {"filter_resonance", 40.0f},
                {"filter_env_amount", 70.0f},
                {"filter_attack", 1.0f},
                {"filter_decay", 0.5f},
                {"filter_sustain", 80.0f},
                {"filter_release", 0.5f},
                {"master_level", -11.1f},
            },
            {{1, "none"}, {2, "none"}, {3, "none"}, {4, "noise"}},
            "lp",
            "poly",
            {{"reverb", true}, {"delay", true}},
        },
        {
            "Laser Zap",
            "FX",
            "Quick descending pitch zap for sci-fi effects",
            {
                {"amp_attack", 0.0f},
                {"amp_decay", 0.15f},
                {"amp_sustain", 0.0f},
                {"amp_release", 0.1f},
                {"level_1", -3.1f},
                {"level_2", -6.0f},
                {"level_3", -100.0f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"tune_2", 24.0f},
                {"detune_1", 0.000f},
                {"detune_2", 0.000f},
                {"filter_freq", 125.0f},
                {"filter_resonance", 50.0f},
                {"filter_env_amount", 80.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.12f},
                {"filter_sustain", 0.0f},
                {"filter_release", 0.05f},
                {"master_level", -9.6f},
            },
            {{1, "saw_up"}, {2, "square"}, {3, "none"}, {4, "none"}},
            "lp",
            "mono",
            {},
        },
        {
            "Metallic Bell",
            "FX",
            "Inharmonic bell tone with long ring",
            {
                {"amp_attack", 0.0f},
                {"amp_decay", 0.8f},
                {"amp_sustain", 0.0f},
                {"amp_release", 0.6f},
                {"level_1", -6.2f},
                {"level_2", -4.4f},
                {"level_3", -6.0f},
                {"level_4", -8.0f},
                {"tune_1", 0.0f},
                {"tune_2", 7.9f},
                {"tune_3", 16.1f},
                {"tune_4", 4.1f},
                {"detune_1", 0.000f},
                {"detune_2", 0.000f},
                {"detune_3", 0.000f},
                {"detune_4", 0.000f},
                {"filter_freq", 125.0f},
                {"filter_resonance", 5.0f},
                {"filter_env_amount", 10.0f},
                {"master_level", -9.6f},
            },
            {{1, "sine"}, {2, "sine"}, {3, "sine"}, {4, "sine"}},
            "lp",
            "poly",
            {{"reverb", true}},
        },
        {
            "Vinyl Crackle",
            "FX",
            "Lo-fi vinyl noise texture for ambient layering",
            {
                {"amp_attack", 0.1f},
                {"amp_decay", 0.2f},
                {"amp_sustain", 80.0f},
                {"amp_release", 0.3f},
                {"level_1", -100.0f},
                {"level_2", -100.0f},
                {"level_3", -100.0f},
                {"level_4", -3.1f},
                {"filter_freq", 101.7f},
                {"filter_resonance", 10.0f},
                {"filter_env_amount", 0.0f},
                {"master_level", -14.4f},
            },
            {{1, "none"}, {2, "none"}, {3, "none"}, {4, "noise"}},
            "lp",
            "poly",
            {},
        },
        // ====================================================================
        // SYNTH / OTHER
        // ====================================================================
        {
            "Wobble",
            "Other",
            "Dubstep wobble bass with heavy filter modulation",
            {
                {"amp_attack", 0.0f},
                {"amp_decay", 0.1f},
                {"amp_sustain", 90.0f},
                {"amp_release", 0.05f},
                {"level_1", -3.1f},
                {"level_2", -3.1f},
                {"level_3", -10.5f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"tune_2", 0.0f},
                {"tune_3", 12.0f},
                {"detune_1", 0.040f},
                {"detune_2", 0.040f},
                {"filter_freq", 101.7f},
                {"filter_resonance", 50.0f},
                {"filter_env_amount", 40.0f},
                {"filter_attack", 0.0f},
                {"filter_decay", 0.3f},
                {"filter_sustain", 30.0f},
                {"filter_release", 0.1f},
                {"master_level", -8.2f},
            },
            {{1, "saw_up"}, {2, "square"}, {3, "saw_up"}, {4, "none"}},
            "lp",
            "mono",
            {{"distortion", true}},
        },
        {
            "Chiptune",
            "Other",
            "8-bit retro game console sound",
            {
                {"amp_attack", 0.0f},
                {"amp_decay", 0.05f},
                {"amp_sustain", 90.0f},
                {"amp_release", 0.02f},
                {"level_1", -3.1f},
                {"level_2", -100.0f},
                {"level_3", -100.0f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"filter_freq", 125.0f},
                {"filter_resonance", 0.0f},
                {"filter_env_amount", 0.0f},
                {"master_level", -9.6f},
            },
            {{1, "square"}, {2, "none"}, {3, "none"}, {4, "none"}},
            "off",
            "mono",
            {},
        },
        {
            "Brass Stab",
            "Other",
            "Punchy brass section stab for funk and disco",
            {
                {"amp_attack", 0.02f},
                {"amp_decay", 0.2f},
                {"amp_sustain", 60.0f},
                {"amp_release", 0.12f},
                {"level_1", -5.0f},
                {"level_2", -3.1f},
                {"level_3", -8.0f},
                {"level_4", -100.0f},
                {"tune_1", 0.0f},
                {"tune_2", 0.0f},
                {"tune_3", 0.0f},
                {"detune_1", 0.020f},
                {"detune_2", 0.020f},
                {"detune_3", 0.000f},
                {"filter_freq", 105.2f},
                {"filter_resonance", 15.0f},
                {"filter_env_amount", 45.0f},
                {"filter_attack", 0.01f},
                {"filter_decay", 0.15f},
                {"filter_sustain", 30.0f},
                {"filter_release", 0.1f},
                {"master_level", -8.2f},
            },
            {{1, "saw_up"}, {2, "saw_up"}, {3, "square"}, {4, "none"}},
            "lp",
            "poly",
            {},
        },
        {
            "Choir Aah",
            "Other",
            "Soft vocal choir pad with breathy texture",
            {
                {"amp_attack", 0.3f},
                {"amp_decay", 0.3f},
                {"amp_sustain", 70.0f},
                {"amp_release", 0.4f},
                {"level_1", -7.5f},
                {"level_2", -6.0f},
                {"level_3", -10.5f},
                {"level_4", -16.5f},
                {"tune_1", 0.0f},
                {"tune_2", 0.0f},
                {"tune_3", 0.0f},
                {"tune_4", 0.0f},
                {"detune_1", 0.020f},
                {"detune_2", 0.020f},
                {"detune_3", 0.040f},
                {"detune_4", 0.040f},
                {"filter_freq", 105.2f},
                {"filter_resonance", 12.0f},
                {"filter_env_amount", 10.0f},
                {"filter_attack", 0.3f},
                {"filter_decay", 0.3f},
                {"filter_sustain", 50.0f},
                {"filter_release", 0.4f},
                {"master_level", -9.6f},
            },
            {{1, "saw_up"}, {2, "saw_up"}, {3, "triangle"}, {4, "noise"}},
            "lp",
            "poly",
            {{"reverb", true}, {"chorus", true}},
        },
    };
    return presets;
}

}  // namespace magda
